/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Thomas Flynn (https://sketchfab.com/nebulousflynn)
License: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
Source: https://sketchfab.com/3d-models/planet-mars-nasa-mars-landing-2021-f735027736264c41b980193ee0aaf651
Title: Planet Mars - NASA Mars Landing 2021
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model({ setTitle, ...props }) {
    const { scene } = useGLTF("/scene.gltf");  
    const modelRef = useRef();

    useFrame(() => {
        if (!modelRef.current) return;

        // Rotate the model smoothly
        modelRef.current.rotation.y += 0.003; // Adjust speed if needed

        // Convert rotation to degrees
        const rotationDeg = ((modelRef.current.rotation.y * 180) / Math.PI) % 360;

        // Determine the title based on rotation angle
        let newTitle = 0;
        if (rotationDeg > 0 && rotationDeg <= 72) newTitle = 0;
        else if (rotationDeg > 72 && rotationDeg <= 144) newTitle = 1;
        else if (rotationDeg > 144 && rotationDeg <= 216) newTitle = 2;
        else if (rotationDeg > 216 && rotationDeg <= 288) newTitle = 3;
        else if (rotationDeg > 288 && rotationDeg <= 359) newTitle = 4;
        else newTitle = 0;

        // Update title when it changes
        if (modelRef.current.lastTitle !== newTitle) {
            modelRef.current.lastTitle = newTitle;
            setTitle(newTitle);
        }
    });

    return (
        <group ref={modelRef} {...props} scale={1.4}>
            <primitive object={scene} />
        </group>
    );
}

useGLTF.preload("/scene.gltf");

